services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
  web-ui:
    image: devdt/shell-yeah-web-ui-service
    deploy:
      mode: replicated
      replicas: 2

  game-ws:
    image: devdt/shell-yeah-game-service
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis

  api-gateway:
    image: nginx:latest
    volumes:
      - ./docker/loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-ui
      - game-ws
    ports:
      - "80:80"

volumes:
  cache:
    driver: local