version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
  game-ws:
    build: .
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
      #     memory: 50M
    depends_on:
      - redis
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./docker/loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - game-ws
volumes:
  cache:
    driver: local
