name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cd ./shell-yeah-server/
    - name: Build the Docker image
      run: docker build . --file ./shell-yeah-server/dockerfile --tag shell-yeah:$(date +%s)
