name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 3: Configure Docker for GCP
      - name: Configure Docker
        run: gcloud auth configure-docker

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/game-ws"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/game-ws"
          gcloud run deploy game-ws \
            --image $IMAGE_NAME \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated
